create database employe1;
use employe1;
create table employe(eio int(10),ename varchar(50),eaddress varchar(50),ecity varchar(50));
Insert into employe values (1,'apoorva','sattenpalli','guntur');
Insert into employe values (2,'priya','austron','us');
Insert into employe values (3,'jhon','mexcio','mexcio');
Insert into employe values (4,'antoni','london','uk');
Insert into employe values (5,'han','berlin','germany');
select distinct eio,ename,eaddress,ecity from employe;
select * from employe;
alter table employe add salary int(10);
alter table employe drop column sal;
select * from employe order by ename; 
update employe set eaddress='london',ecity='uk' where eio=1;
update employe set salary=10000 where ename='apoorva';
update employe set salary=20000 where ename='priya';
update employe set salary=80000 where ename='jhon';
update employe set salary=50000 where ename='antoni';
update employe set salary=60000 where ename='han';
select * from employe where salary between 10000 and 50000;
select * from employe where salary<60000;
select * from employe where salary>60000;
select * from employe where salary>=60000;
select * from employe where salary<=60000;
select * from employe where salary<> 60000;
select * from employe where ecity like 'm%';
select * from employe where ecity In ('london','uk');
select * from employe where ename like '%a';
select * from employe where ename like '%or%';
select * from employe where ename like '_r%';
select * from employe where eaddress like 'b_%';
select * from employe where ecity like 'u__%';
select * from employe where ecity like 'm__%';
select * from employe where eaddress like 'a%n';
select * from employe where ecity='mexcio' and ename='jhon';
select * from employe where ecity='mexcio' or ename='apoorva';
select * from employe where not ecity='mexcio';
select * from employe where not ecity='mexcio' or ename='apoorva';
select * from employe where  not ecity='mexcio' and ename='jhon';
select * from employe order by eaddress;
select * from employe order by ename desc;
delete from employe where ename='apoorva';
select top3 * from employe;
